apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: go-app
  namespace: telerik
spec:
  interval: 5m
  chart:
    spec:
      chart: ./.deployment/go-app-chart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: go-app
        namespace: flux-system
      valuesFiles:
        - values.yaml
  values:
    image: docker.io/stroming/final-project-telerik:master-d991358c7fc35f6999e802e478a95fb8bb89c10a # {"$imagepolicy": "flux-system:go-app"}
