---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: go-app
  namespace: flux-system
spec:
  filterTags:
    extract: ""
    pattern: ^master-[a-f0-9]{10}$
  imageRepositoryRef:
    name: go-app
  policy:
    alphabetical:
      order: asc