apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app-container
          image: docker.io/stroming/final-project-telerik:master-d991358c7fc35f6999e802e478a95fb8bb89c10a # {"$imagepolicy": "flux-system:go-app"}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3333
              protocol: TCP
