---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prod
  namespace: telerik
spec:
  interval: 5m
  chart:
    spec:
      chart: ./.deployment/production-chart
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: go-app
        namespace: flux-system
      valuesFiles:
        - values.yaml
  values:
    image: docker.io/stroming/final-project-telerik:latest # {"$imagepolicy": "flux-system-prod:go-app"}
